Issue #328: fix for validationType for non base token properties
checkstyle/sonar-checkstyle pull request #330
Opened 2020-09-05 17:18 UTC by gaurabdg

Issue #328 
DescendantTokenCheck
<img width="970" alt="Screenshot 2020-09-05 at 9 29 24 PM" src="https://user-images.githubusercontent.com/23253816/92310224-e48afb80-efc9-11ea-9bcb-0486f52ea32f.png">

MultipleStringLiteralsCheck
<img width="970" alt="Screenshot 2020-09-05 at 9 32 02 PM" src="https://user-images.githubusercontent.com/23253816/92310226-e81e8280-efc9-11ea-9637-2feaff151845.png">

MagicNumberCheck
<img width="970" alt="Screenshot 2020-09-05 at 10 03 16 PM" src="https://user-images.githubusercontent.com/23253816/92310227-ebb20980-efc9-11ea-9c35-bf1e14cd1567.png">

IllegalTypeCheck
<img width="704" alt="Screenshot 2020-09-05 at 10 09 22 PM" src="https://user-images.githubusercontent.com/23253816/92310229-eeacfa00-efc9-11ea-8abd-cc3415d306c0.png">

AtclauseOrderCheck
<img width="1013" alt="Screenshot 2020-09-05 at 3 53 41 AM" src="https://user-images.githubusercontent.com/23253816/92310231-f2d91780-efc9-11ea-8a63-8db5e317b044.png">

2020-09-06 15:10 UTC, romani commented
https://checkstyle.org/config_misc.html#DescendantToken

`tokens` is not referenced in javadoc and xdoc.
We usually have such model ONLY for cases when `tokens` is not configurable (getRequredToekns == getAcceptableTokens).
but this is different case, we just need all tokens. We might did not wanted to list all tokens, as it is too much we were too lazy.
Lets do some HACK to unblock us:
please introduce `tokens` to javadoc and make new type `all tokens TokenTypes`
and please make all required hacks in UTs to make them appear in metafiles as list of all tokens or just as type `allTokenTypes` to let plugins treat them in special way.

2020-09-12 10:55 UTC, muhlba91 approved these changes

2020-09-12 10:56 UTC, muhlba91 commented
please check build failures :)

2020-09-12 14:19 UTC, romani requested changes
items:

2020-09-12 14:19 UTC, romani commented on pom.xml
> +    <checkstyle.version>8.37-SNAPSHOT</checkstyle.version>
please use 8.36.1, it is released

2020-09-12 16:27 UTC, gaurabdg commented on pom.xml
> +    <checkstyle.version>8.37-SNAPSHOT</checkstyle.version>
Done

2020-09-12 16:30 UTC, romani commented
Wercker is failed in sonar validation
`Cloning into 'blog-sonar-build-breaker'...
Timeout of  + 36 +  seconds exceeded`

The same problem is in checkstyle repo, I am not sure why ...

2020-09-12 18:04 UTC, merged